package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.25

import (
	"context"
	"fmt"
	"time"

	"github.com/jlwt90/gqlgen-usage-analysis/graph/model"
)

// Teacher is the resolver for the teacher field.
func (r *classResolver) Teacher(ctx context.Context, obj *model.Class) (*model.User, error) {
	if obj.ID == "C1" {
		return &model.User{
			ID:    "U1",
			Name:  "U1",
			Class: &model.Class{ID: "C1"},
		}, nil
	}
	return &model.User{
		ID:    "U2",
		Name:  "U2",
		Class: &model.Class{ID: "C2"},
	}, nil
}

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	return &model.Todo{
		ID:   input.UserID,
		Text: input.Text,
		Done: false,
		User: nil,
	}, nil
}

// Todos is the resolver for the todos field.
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	return []*model.Todo{
		{
			ID:         "T1",
			Text:       "t1",
			Done:       false,
			User:       nil,
			AssignedTo: &model.User{ID: "U1", Name: "N1"},
		},
		{
			ID:         "T2",
			Text:       "t2",
			Done:       true,
			User:       nil,
			AssignedTo: &model.User{ID: "U1", Name: "N1"},
		},
		{
			ID:         "T3",
			Text:       "t3",
			Done:       true,
			User:       nil,
			AssignedTo: &model.User{ID: "U1", Name: "N1"},
		},
	}, nil
}

// Todo is the resolver for the todo field.
func (r *queryResolver) Todo(ctx context.Context, id string) (*model.Todo, error) {
	var obj *model.Todo
	if id == "T1" {
		obj = &model.Todo{
			ID:         "T1",
			Text:       "t1",
			Done:       false,
			User:       nil,
			AssignedTo: &model.User{ID: "U1", Name: "N1"},
		}
	} else if id == "T2" {
		obj = &model.Todo{
			ID:         "T2",
			Text:       "t2",
			Done:       true,
			User:       nil,
			AssignedTo: &model.User{ID: "U1", Name: "N1"},
		}
	} else if id == "T3" {
		obj = &model.Todo{
			ID:         "T3",
			Text:       "t3",
			Done:       true,
			User:       nil,
			AssignedTo: &model.User{ID: "U1", Name: "N1"},
		}
	}
	return obj, nil
}

// CurrentTime is the resolver for the currentTime field.
func (r *subscriptionResolver) CurrentTime(ctx context.Context) (<-chan *model.Time, error) {
	// First you'll need to `make()` your channel. Use your type here!
	ch := make(chan *model.Time)

	// You can (and probably should) handle your channels in a central place outside of `schema.resolvers.go`.
	// For this example we'll simply use a Goroutine with a simple loop.
	go func() {
		for {
			// In our example we'll send the current time every second.
			time.Sleep(1 * time.Second)
			fmt.Println("Tick")

			// Prepare your object.
			currentTime := time.Now()
			t := &model.Time{
				UnixTime:  int(currentTime.Unix()),
				TimeStamp: currentTime.Format(time.RFC3339),
			}

			// The channel may have gotten closed due to the client disconnecting.
			// To not have our Goroutine block or panic, we do the send in a select block.
			// This will jump to the default case if the channel is closed.
			select {
			case ch <- t: // This is the actual send.
				// Our message went through, do nothing
			default: // This is run when our send does not work.
				fmt.Println("Channel closed.")
				// You can handle any deregistration of the channel here.
				return // We'll just return ending the routine.
			}
		}
	}()

	// We return the channel and no error.
	return ch, nil
}

// User is the resolver for the user field.
func (r *todoResolver) User(ctx context.Context, obj *model.Todo) (*model.User, error) {
	if obj.ID == "T1" {
		return &model.User{
			ID:   "U1",
			Name: "u1",
		}, nil
	} else if obj.ID == "T2" {
		return &model.User{
			ID:   "U2",
			Name: "u2",
		}, nil
	}
	return &model.User{
		ID:   "U3",
		Name: "u3",
	}, nil
}

// Class is the resolver for the class field.
func (r *userResolver) Class(ctx context.Context, obj *model.User) (*model.Class, error) {
	if obj.ID == "U1" {
		return &model.Class{
			ID:   "C1",
			Name: "Class1",
		}, nil
	} else {
		return &model.Class{
			ID:   "C2",
			Name: "Class2",
		}, nil
	}
}

// Class returns ClassResolver implementation.
func (r *Resolver) Class() ClassResolver { return &classResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

// Todo returns TodoResolver implementation.
func (r *Resolver) Todo() TodoResolver { return &todoResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type classResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
type todoResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
