// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Class struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	Teacher *User  `json:"teacher"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Time struct {
	UnixTime  int    `json:"unixTime"`
	TimeStamp string `json:"timeStamp"`
}

type Todo struct {
	ID         string `json:"id"`
	Text       string `json:"text"`
	Done       bool   `json:"done"`
	User       *User  `json:"user"`
	AssignedTo *User  `json:"assignedTo"`
}

type User struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Class *Class `json:"class"`
}
